"""Build navigation from the approved transparent island (requires Pillow).

Run from repository root: python tools/asset-studio/fleet-raster-mask.py
Only reads the art; it never alters it. 0 = land, 1 = sea, 2 = lagoon.
"""
from pathlib import Path
from collections import deque
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
N = 125
im = Image.open(ROOT / 'public/assets/fleet-base-approved-v1.webp').convert('RGBA')
alpha = im.getchannel('A')
land = []
for y in range(N):
    for x in range(N):
        samples = [alpha.getpixel((min(im.width-1, int((x+sx)*im.width/N)),
                                   min(im.height-1, int((y+sy)*im.height/N))))
                   for sx in (.2,.5,.8) for sy in (.2,.5,.8)]
        land.append(sum(a > 96 for a in samples) >= 3)
# One-cell clearance for the ship centre at visible shorelines.
blocked = [any(land[ny*N+nx]
               for ny in range(max(0,y-1),min(N,y+2))
               for nx in range(max(0,x-1),min(N,x+2)))
           for y in range(N) for x in range(N)]
open_water = set()
queue = deque()
for y in range(N):
    for x in range(N):
        k = y*N+x
        if (x in (0,N-1) or y in (0,N-1)) and not blocked[k]:
            open_water.add(k); queue.append(k)
while queue:
    k = queue.popleft(); x,y = k%N,k//N
    for nx,ny in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
        j = ny*N+nx
        if 0<=nx<N and 0<=ny<N and j not in open_water and not blocked[j]:
            open_water.add(j); queue.append(j)
values = []
for k in range(N*N):
    x,y = (k%N+.5)*8-500,(k//N+.5)*8-500
    inside = -190<x<190 and -120<y<400
    values.append((2 if inside else 1) if k in open_water else 0)
assert values[70*N+62] == 2, 'Lagoon must connect to the open sea'
def base36(n):
    out=''
    while n: out='0123456789abcdefghijklmnopqrstuvwxyz'[n%36]+out; n//=36
    return out or '0'
runs=[]; cur=values[0]; count=0
for value in values:
    if value==cur: count+=1
    else: runs.append(str(cur)+base36(count));cur=value;count=1
runs.append(str(cur)+base36(count))
(ROOT/'src/fleetMask.ts').write_text(
    '// Generated by tools/asset-studio/fleet-raster-mask.py from approved v1 alpha.\n'
    '// 125 x 125 cells, 8 world units; origin (-500,-500). 0 land, 1 sea, 2 lagoon.\n'
    "export const FLEET_MASK={n:125,cell:8,rle:'"+','.join(runs)+"'};\n")
print(f'Navigation: {values.count(0)} land, {values.count(1)} sea, {values.count(2)} lagoon cells')
